<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFZi9NnC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFZi9NnC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFZi9NnC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFZi9NnC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFZi9NnC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FZi9NnC',
    'container.build_id' => '61ab6fee',
    'container.build_time' => 1568798982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFZi9NnC');
