<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrvxL1A\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrvxL1A/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCrvxL1A.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCrvxL1A\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCrvxL1A\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CrvxL1A',
    'container.build_id' => '8ef7346c',
    'container.build_time' => 1569416358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrvxL1A');
