<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAColpO1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAColpO1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAColpO1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAColpO1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAColpO1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AColpO1',
    'container.build_id' => '4fba9492',
    'container.build_time' => 1569406725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAColpO1');
